### ISSUE TITLE
the tests are broken for this lab

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/simple-partials-reading#3]
I am not able to get anything to pass in the labs, but when I run the server everything works as planned.

**Comment by MitulMistry** [comment]
The tests don't create authors, so when @author.name is called in the partial, it breaks.

**Comment by c1505** [comment]
Same.  Works in the browser.  Deleted the tests and moving on.

**Comment by coltonstaab1** [comment]
I'm still having the same issue

**Comment by AnnJohn** [comment]
Thanks @coltonstaab1. Will loo, at this soon.

**Comment by AnnJohn** [comment]
these should be updated. thanks!
